### ISSUE TITLE
Schematics pdf

### ISSUE THREAD

**Issue by jaksatomovic** [dronecz/Minimal_carrier_board_for_CM4#1]
Can you please share schematics in pdf format, since this can't be opened in KiCad? Thx

**Comment by dronecz** [comment]
HI, 

I can, but which version you have in mind? I do not use it, but I know that KiCad can import Eagle projects.

**Comment by jaksatomovic** [comment]
Hi, thx for the quick reply. I was thinking on latest version…C

**Comment by dronecz** [comment]
[Here](https://github.com/dronecz/Minimal_carrier_board_for_CM4/blob/main/rev_C/Minimal_carrier_board_for_CM4_rev_C.pdf) you have it 😉

**Comment by jaksatomovic** [comment]
Thank you!
